# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amuse < Formula
  desc "amuse controls Apple Music (Music.app) from the terminal on macOS, via AppleScript."
  homepage "https://github.com/o-ga09/amuse"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/o-ga09/amuse/releases/download/v0.0.1/amuse_v0.0.1_darwin_amd64.tar.gz"
    sha256 "5b09082471a2b8e72a1604dbc4c916fbf53bb4ea29d0858f8939dea8b363f725"

    define_method(:install) do
      bin.install "amuse"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/o-ga09/amuse/releases/download/v0.0.1/amuse_v0.0.1_darwin_arm64.tar.gz"
    sha256 "2b4c2c60e98a7a64bf595c12227b2a1854768ff41eafb2ef0085d4ec55903416"

    define_method(:install) do
      bin.install "amuse"
    end
  end

  test do
    system "#{bin}/amuse --version"
  end
end
